export const MIXTAPE_PIPELINE = {
  initialRecommendationCount: 5,
  maximumInitialRecommendations: 6,
  targetVerifiedTracks: 5,
  minimumVerifiedTracks: 3,
  maximumReplacementRounds: 1,
  serverBudgetMs: 35_000,
  stopBufferMs: 1_000,
  itunesConcurrency: 3,
  maximumMusicBrainzChecks: 3,
  rawCandidateTarget: 25,
  minimumRawCandidates: 20,
  maximumRawCandidates: 30,
  shortlistTarget: 15,
  minimumShortlistCandidates: 12,
  maximumShortlistCandidates: 15,
  maximumItunesSearches: 6,
  maximumMusicBrainzRequests: 3,
} as const
